---
name: R-CMD-check

on:
   - push
   - pull_request

jobs:
   R-CMD-check:
      runs-on: ubuntu-latest

      container:
         image: blcdsdockerregistry/bl-r-devel:latest

      steps:
         - uses: actions/checkout@v2
           with:
              path: DigITx
         - name: Build package
           - run: R CMD build --compact-vignettes="gs+qpdf" DigITx
         - name: Check package
           - run: R CMD check --as-cran --run-donttest DigITx_*.tar.gz
         - name: Install and run scripts
           - run: Rscript -e 'install.packages("devtools"); devtools::install_local(dependencies = T, force = T); source("inst/run_all_analyses")'
